### ISSUE TITLE
Viewing issues when logged in

### ISSUE THREAD

**Issue by colehudson** [WSULib/digitalcollections#17]
Seems to be some issues with viewing items at the single record page when logged in. Logging out fixes it, but sounds like there is a weird persistent session/cookie that's fouling up things.

**Comment by ghukill** [comment]
Adding additional tolerance to datastreams not loading tokens, but leaving issue open as not yet confirmed what problem is.  Doesn't appear to be race condition as originally suspected...

**Comment by ghukill** [comment]
Fixed with new admin view.
