### ISSUE TITLE
figure out way to serve static HTML, PHP, etc. files from server

### ISSUE THREAD

**Issue by ghukill** [WSULib/digitalcollections#19]
As the new v2 configurations change the document root to `/public` in the digital collections, it would be handy to have a location or method for serving static files once in awhile.

I suppose we could dump things to the `/public` folder and that would work, but they would potentially clash with Slim routes.  But maybe that's not the end of the world...

**Comment by colehudson** [comment]
Haven't tried it yet, but I think we can do it.

See: http://stackoverflow.com/questions/12483257/serving-a-directory-outside-documentroot-with-apache

**Comment by ghukill** [comment]
Perfect. Closing!
